
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

loop_src=Split('loop_bundle.cpp loop_file.cpp loop_slice.cpp loop_pinger.cpp loop_clicker.cpp')
env.PiSharedLibrary('piloop',loop_src,libraries=Split('pic piw pie pia pisamplerate'),package='eigend',per_agent='plg_loop',locked=True)
env.PiPipBinding('loop_native','loop.pip',libraries=Split('piloop pic piw pie pia pisamplerate'),package='eigend',per_agent='plg_loop')
