
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

native_files = Split("""host.cpp""")
env.PiSharedLibrary('pihost',native_files,libraries=Split('juce ejuce pia piw pic pie midilib'),package='eigend',per_agent='plg_host')
env.PiPipBinding('host_native','host.pip',libraries=Split('pihost juce pia piw pic pie midilib'),package='eigend',per_agent='plg_host')

env.Append(PI_HIRES=True)

scanner_files = Split("scan.cpp")
env.PiGuiProgram('scanner0',scanner_files,appname='EigenScanner0',package='eigend',libraries=Split('juce ejuce pic pia pie'),private=True,di=True)

scanctl_files = Split("scanctl.cpp JucerScanCtlComponent.cpp JucerScanPrgComponent.cpp JucerScanCompleteComponent.cpp")
env.PiGuiProgram('scanner',scanctl_files,appname='EigenScanner',package='eigend',libraries=Split('juce ejuce pic pia pie'),private=True)

if env['IS_MACOSX']:
    env.PiEtc('eigend',Split('postflight-host'))

if env['IS_WINDOWS']:
    env.PiPackageInit('eigend','scanner',as_user=True)
