
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')
env.PiSharedLibrary('micro',Split('micro_active.cpp micro_passive.cpp micro_fastmark.cpp'),libraries=Split('pic pico_decoder_1_0_0'),package='eigend')
env.PiProgram('microraw','microraw.cpp',libraries=Split('pic micro'))
env.PiProgram('ustripcal','stripcal.cpp',libraries=Split('pic micro'))
env.PiPipBinding('micro_native','micro.pip',libraries=Split('pic micro'),package='eigend')
