#!/bin/sh

su $USER -c $PI_PREFIX/bin/upgrade_user

XXX=`echo $PI_RELEASE | sed 's/-stable$//'`

if [ "$XXX" != "$PI_RELEASE" ]
then
    rm -rf "/Applications/EigenD.app" 
    rm -rf "/Applications/EigenBrowser.app" 
    mkdir -p "/Applications/Eigenlabs"
    cp -R "/Applications/Eigenlabs/$PI_RELEASE/EigenD.app" "/Applications/EigenDx.app" 
    mv "/Applications/EigenDx.app" "/Applications/EigenD.app" 
fi
