
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

paenv = env.Clone()

plg_files = Split("""
    audio_juce.cpp AudioDialogComponent.cpp
""")

plg_libs = Split("""
    pic piw pie pia pijuce
""")

paenv.Append(CPPPATH='../../lib_juce/modules')
paenv.PiPipBinding('audio_native','audio.pip',libraries=plg_libs,sources=plg_files,package='eigend',per_agent='plg_audio',locked=True)
