
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

midilib_files=Split("""
	midi_decoder.cpp midi_from_belcanto.cpp midi_input_port.cpp
	midi_output_port.cpp
	control_mapper_gui.cpp midi_converter.cpp control_mapping.cpp
    control_params.cpp JucerPopupDialogComponent.cpp
    JucerCellPopupComponent.cpp JucerGlobalSettingsComponent.cpp JucerHelpComponent.cpp
	SliderEx.cpp
    """)

midilib_env=env.Clone()


midilib_env.Append(CPPPATH='../../lib_juce/modules')
midilib_env.PiSharedLibrary('midilib',midilib_files,libraries=Split('pia pic pie piw pijuce'),package='eigend',public=True,locked=True)

midilib_py=env.Clone()
midilib_py.Append(CPPPATH='../../lib_juce/modules')
midilib_py.PiPipBinding('midilib_native',env.Pipfile('midilib.pip'),libraries=Split('midilib pic pia pie piw pijuce'),package='eigend')
