
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiResources('rig','rigs/*',package='eigend')
env.PiResources('upgrades','upgrades/*',package='eigend')
env.PiResources('audiounit','aupresets/*',package='eigend')

env.PiResources('Scripts/Arranger','scripts/Arranger/*',package='eigend') 
env.PiResources('Scripts/AU Inline FX GUI show','scripts/AU Inline FX GUI show/*',package='eigend')
env.PiResources('Scripts/Direct Monitoring','scripts/Direct Monitoring/*',package='eigend') 
env.PiResources('Scripts/Factory Setup Fixes','scripts/Factory Setup Fixes/*',package='eigend') 
env.PiResources('Scripts/Interpreter','scripts/Interpreter/*',package='eigend')
env.PiResources('Scripts/Keyboard Layout','scripts/Keyboard Layout/*',package='eigend')
env.PiResources('Scripts/Keygroup','scripts/Keygroup/*',package='eigend') 
env.PiResources('Scripts/Lights','scripts/Lights/*',package='eigend')
env.PiResources('Scripts/Metronome','scripts/Metronome/*',package='eigend') 
env.PiResources('Scripts/Midi Outputs','scripts/Midi Outputs/*',package='eigend') 
env.PiResources('Scripts/Octave Key Transposition','scripts/Octave Key Transposition/*',package='eigend')
env.PiResources('Scripts/Pan Curve','scripts/Pan Curve/*',package='eigend') 
env.PiResources('Scripts/Pitch Bend','scripts/Pitch Bend/*',package='eigend')
env.PiResources('Scripts/Plug-in','scripts/Plug-in/*',package='eigend')
env.PiResources('Scripts/Sampler Release','scripts/Sampler Release/*',package='eigend')
env.PiResources('Scripts/Strummer','scripts/Strummer/*',package='eigend') 

env.PiResources('Help','documentation.xml',package='eigend') 

if env['IS_WINDOWS']:
    env.PiResources('state','states_win/*',package='eigend')
    env.PiResources('example','examples_win/*',package='eigend')
    env.PiReleaseFile('eigend','releasenotes.pdf','Release Notes')
    env.PiReleaseFile('eigend','pico-setup.pdf','Pico Setup Guide')
    env.PiReleaseFile('eigend','alpha-setup.pdf','Alpha Setup Guide')
    env.PiReleaseFile('eigend','tau-setup.pdf','Tau Setup Guide')
else:
    env.PiResources('state','states_mac/*',package='eigend')
    env.PiResources('example','examples_mac/*',package='eigend')

if env['IS_MACOSX']:
    env.PiEtc('eigend',Split('postflight-docs'))
    env.PiEtc('eigend',Split('releasenotes.pdf'))
    env.PiEtc('eigend',Split('pico-setup.pdf'))
    env.PiEtc('eigend',Split('alpha-setup.pdf'))
    env.PiEtc('eigend',Split('tau-setup.pdf'))
    env.PiEtc('eigend',Split('sfpatch'))

