
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiPythonPackage(resources=Split('accent.wav beat.wav *.png'),package='eigend',per_agent='plg_loop')
env.PiAgent('metronome','plg_loop','metronome_plg',cversion='1.0.0')
env.PiAgent('drummer','plg_loop','drummer_plg',cversion='1.0.1')
env.PiAgent('clicker','plg_loop','clicker_plg',cversion='1.0.0')
#env.PiPythonWrapper('loopdb_create','plg_loop','loopdb','create',package='eigend')

#if env['IS_MACOSX']:
#    env.PiEtc('eigend',Split('postflight-loop'))

#if env['IS_WINDOWS']:
#    env.PiPackageInit('eigend','loopdb_create',as_user=True)
