
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiPythonPackage('0.0',natives=Split('loop_native'),resources=Split('accent.wav beat.wav *.png'),pi='0.0',package='eigend')
env.PiAgent('metronome','plg_loop.metronome_plg','plg_loop:0.0',cversion='1.0.0',package='eigend')
env.PiAgent('drummer','plg_loop.drummer_plg','plg_loop:0.0',cversion='1.0.1',package='eigend')
env.PiAgent('clicker','plg_loop.clicker_plg','plg_loop:0.0',cversion='1.0.0',package='eigend')
env.PiAgent('audio_player','plg_loop.audio_player_plg','plg_loop:0.0',cversion='1.0.0',package='eigend')
env.PiPythonWrapper('loopdb_create','plg_loop','loopdb','create',package='eigend')

if env['IS_MACOSX']:
    env.PiEtc('eigend',Split('postflight-loop'))

if env['IS_WINDOWS']:
    env.PiPackageInit('eigend','loopdb_create',as_user=True)
