
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiPythonPackage(resources=Split('*.png'),package='eigend',per_agent=True)

env.PiResources('eigend','upgrade_manager','script_*')
env.PiResources('eigend','scale_manager','User Scales.txt')

env.PiAgent('cycler','plg_simple','cycler_plg',cversion='1.0.0')
env.PiAgent('scaler','plg_simple','scaler_plg',cversion='1.0.1')
env.PiAgent('stringer','plg_simple','stringer_plg',cversion='1.0.1')
env.PiAgent('scheduler','plg_simple','scheduler_plg',cversion='1.0.0')
env.PiAgent('keygroup','plg_simple','keygroup_plg',cversion='1.0.3',extra=['kgroup'])
env.PiAgent('scale_manager','plg_simple','scale_manager_plg',cversion='1.0.0')
env.PiAgent('talker','plg_simple','talker_plg',cversion='1.0.2')
env.PiAgent('ranger','plg_simple','ranger_plg',cversion='1.0.0')
env.PiAgent('strummer','plg_simple','strummer_plg',cversion='1.0.0')
