
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiSharedLibrary('alpha2',Split('alpha2_passive.cpp alpha2_active.cpp alpha2_fastmark.cpp'),libraries=Split('pic'),package='eigend')

env.PiProgram('a2dump','a2dump.cpp',libraries=Split('pic alpha2'))
env.PiProgram('audio_test','audio_test.cpp',libraries=Split('pic alpha2'))

env.PiPipBinding('alpha2_native',env.Pipfile('alpha2.pip'),libraries=Split('pic alpha2'),package='eigend')


