
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

plg_convolver_files=Split("""
    plg_convolver.cpp zita_convolver.cpp
""")

env.PiSharedLibrary('convolver',plg_convolver_files,libraries=Split('pisamplerate pifftw3 pic piw pie pia'),package='eigend',hidden=False,per_agent='plg_convolver')
env.PiPipBinding('convolver_native','plg_convolver.pip',libraries=Split('convolver pisamplerate pifftw3 pic piw pie pia'),package='eigend',per_agent='plg_convolver')
