
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

pc_env=env.Clone()

plg_convolver_files=Split("""
    plg_convolver.cpp zita_convolver.cpp
""")

pc_libs=Split('pisamplerate pic piw pie pia');

if env['IS_LINUX_ARMV7L']:
   pc_env.Append(LIBS=Split('libfftw3'))
   pc_libs=Split('pisamplerate pic piw pie pia');
else:
   pc_libs=Split('pifftw3 pisamplerate pic piw pie pia');

pc_env.PiSharedLibrary('convolver',plg_convolver_files,libraries=pc_libs,package='eigend',hidden=False,per_agent='plg_convolver')
pc_env.PiPipBinding('convolver_native','plg_convolver.pip',libraries=Split('convolver')+pc_libs,package='eigend',per_agent='plg_convolver')
