#
# Copyright 2011 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiPythonPackage('0.0', natives=Split('primitive_native'), package='eigend')

env.PiAgent('latch', 'plg_primitive.latch_plg', 'plg_latch:0.0', cversion='0.0.1', package='eigend')
env.PiAgent('orb', 'plg_primitive.orb_plg', 'plg_orb:0.0', cversion='0.0.1', package='eigend')
