
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')
env.PiPythonPackage('0.0',natives=Split('recorder_native'),resources=Split('recorder.png'),pi='0.0',pisession='0.0',package='eigend')
env.PiPythonWrapper('brecdump','plg_recorder','recdump','main')
env.PiAgent('recorder','plg_recorder.recorder_plg','plg_recorder:0.0',cversion='1.0.1',package='eigend')
