
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiPythonPackage(package='eigend', resources=Split('mixer.png'),per_agent='plg_synth')

env.PiAgent('ahdsr','plg_synth','ahdsr_plg',cversion='1.0.0')
env.PiAgent('envelope','plg_synth','envelope_plg',cversion='1.0.0')
env.PiAgent('gain','plg_synth','gain_plg',cversion='1.0.0')
env.PiAgent('panner','plg_synth','panner_plg',cversion='1.0.0')
env.PiAgent('rectangle_oscillator','plg_synth','rectangle_oscillator_plg',cversion='1.0.0')
env.PiAgent('sawtooth_oscillator','plg_synth','sawtooth_oscillator_plg',cversion='1.0.0')
env.PiAgent('shaper','plg_synth','shaper_plg',cversion='1.0.0')
env.PiAgent('summer','plg_synth','summer_plg',cversion='1.0.0')
env.PiAgent('synth_filter','plg_synth','synth_filter_plg',cversion='1.0.0')
env.PiAgent('ladder_filter','plg_synth','ladder_filter_plg',cversion='1.0.0')
env.PiAgent('triangle_oscillator','plg_synth','triangle_oscillator_plg',cversion='1.0.0')
env.PiAgent('sine_oscillator','plg_synth','sine_oscillator_plg',cversion='1.0.0')
env.PiAgent('delay','plg_synth','delay_plg',cversion='1.0.0')
env.PiAgent('console_mixer','plg_synth','console_mixer_plg',cversion='1.0.2')
env.PiAgent('polyphonic_summer','plg_synth','polyphonic_summer_plg',cversion='1.0.0',extra=['poly_summer'])
