
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#


Import('env')


synthfiles = Split("""
    synth_blepdata.cpp synth_minblep.cpp synth_adsr.cpp
    synth_wavetable.cpp synth_sinetable.cpp 
    synth_filter.cpp synth_shaper.cpp synth_adsr2.cpp
    synth_filter2.cpp synth_fastmark.cpp
    """)

if env['IS_MACOSX']:
    env.Append(LINKFLAGS='-framework vecLib')

env.PiSharedLibrary('pisynth',synthfiles, libraries=Split('pic piw pie pia'),package='eigend')
env.PiPipBinding('synth_native','synth.pip',libraries=Split('pisynth pic piw pie pia'),package='eigend')
