Import('env')

#
# Build a shared library called t3d_plg.
#
env.PiSharedLibrary('t3d_plg', 
	Split('t3d_output.cpp t3d_device.cpp Madrona/SoundplaneOSCOutput.cpp'),
	libraries=Split('pic piw pia piop'), 
	package='eigend', per_agent='plg_t3d')

#
# Build a Python native module as described by t3d_plg.pip, called t3d_plg_native.
# Link it against our new shared library and other base libraries
#
env.PiPipBinding('t3d_plg_native', 't3d_plg.pip', libraries=Split('t3d_plg pic piw'), package='eigend', per_agent='plg_t3d')
