
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

plg_files=Split(""" 
    midi_merge_output.cpp midi_input.cpp midi_clock.cpp
    midi_output_juce.cpp midi_input_juce.cpp
""")

plg_libs=Split("""
    pic piw pie pia juce midilib
""")

env.PiSharedLibrary('pimidi',plg_files,plg_libs,package='eigend',per_agent='plg_midi')
env.PiPipBinding('midi_native','midi.pip',libraries=Split('pimidi')+plg_libs,package='eigend',per_agent='plg_midi')
