
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiPythonPackage(per_agent='plg_finger',resources=('Factory Fingerings.txt','User Fingerings.txt'))
env.PiAgent('fingerer','plg_finger','finger_plg',cversion='1.0.0')
env.PiResources('fingerer','User Fingerings.txt')

#env.PiResources('fingerer','Factory Fingerings.txt',package='eigend-nongpl')
