
#
# Copyright 2009 Eigenlabs Ltd.  http://www.eigenlabs.com
#
# This file is part of EigenD.
#
# EigenD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# EigenD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with EigenD.  If not, see <http://www.gnu.org/licenses/>.
#

Import('env')

env.PiPythonPackage(package='eigend',per_agent='plg_midi')
env.PiAgent('midi_output','plg_midi','midi_output_plg',cversion='1.0.0')
env.PiAgent('midi_converter','plg_midi','midi_converter_plg',cversion='1.0.5')
env.PiAgent('midi_clock','plg_midi','midi_clock_plg',cversion='1.0.0')
env.PiAgent('midi_input','plg_midi','midi_input_plg',cversion='1.0.0')
env.PiAgent('midi_processor','plg_midi','midi_processor_plg',cversion='1.0.0')
env.PiAgent('midi_program_chooser','plg_midi','midi_pgm_chooser_plg',cversion='1.0.0')

